export * from './templates/Board/Index.jsx';
export * from './templates/account/Login.jsx';
export * from './templates/account/Register.jsx';
export * from './templates/user/Index.jsx';
export * from './templates/user/Details.jsx';
export * from './templates/notification/Index.jsx';
export * from './templates/message/Index.jsx';
export * from './templates/friend/Index.jsx';
export * from './templates/home/Index.jsx';